receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  # debug: # debug de exports, pode ser usado no lugar do otlphttp nas pipelines
    # verbosity: detailed
  otlphttp:
    endpoint: https://otlp.nr-data.net
    headers:
      api-key: <YOUR_API_KEY>

# extensions: # extensions para ajuda em troubleshooting
  # zpages:
    # endpoint: 0.0.0.0:55679
  # health_check:

service:
  telemetry:
    logs: # logs para debug do collector
      level: "info" # trocar para debug, caso preciso
  # extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp] # podemos trocar para [debug] para usar o exporter debug
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp] # podemos trocar para [debug] para usar o exporter debug
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp] # podemos trocar para [debug] para usar o exporter debug
